version: "3.9"
services:
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:8.6.2
    container_name: elasticsearch
    volumes:
      - elasticsearch-data:/usr/share/elasticsearch/data
    ports:
      - "9200:9200"
      - "9300:9300"
    restart: always
    environment:
      - discovery.type=single-node
      - xpack.security.enabled=false
      - xpack.security.enrollment.enabled=false
      - ES_JAVA_OPTS=-Xms512m -Xmx512m
      - ELASTIC_PASSWORD=changeme
#      - ELASTIC_USERNAME=elastic/fleet-server
      - ELASTICSEARCH_PORT=9200
    networks:
        - elastic

  kibana:
    image: docker.elastic.co/kibana/kibana:8.6.2
    container_name: kibana
    volumes:
      - kibana-data:/usr/share/kibana/data
    ports:
      - "5601:5601"
    restart: on-failure
    environment:
#      ELASTICSEARCH_HOSTS: '["http://elasticsearch:9200","http://elasticsearch:9300"]'
#      ELASTIC_PASSWORD: "changeme"
#      ELASTIC_USERNAME: "elastic"
          - ELASTICSEARCH_HOSTS=http://elasticsearch:9200
          - XPACK_MONITORING_ENABLED=true
          - XPACK_MONITORING_COLLECTION_ENABLED=true
          - ELASTICSEARCH_USERNAME=elastic/kibana
          - ELASTICSEARCH_PASSWORD=changeme
    networks:
      - elastic

volumes:
  elasticsearch-data:
    driver: local
  kibana-data:
    driver: local
networks:
  elastic:
    driver: bridge